#!/bin/bash

clear ; echo "Execute como root! " ; echo Pressione ENTER para continuar ou CTRL+C para encerrar... " ; echo ; read tc

mkdir -p /opt/nvidia304 ; cd /opt/nvidia304
#wget http://us.download.nvidia.com/XFree86/Linux-x86_64/304.137/NVIDIA-Linux-x86_64-304.137.run ; wget https://adufray.com/nvidia-304.137-bionic-18.04.patch
./NVIDIA-Linux-x86_64-304.137.run -x
cd ./NVIDIA-Linux-x86_64-304.137
cp -v .../nvidia-304.137-bionic-18.04.patch
patch -p1 < nvidia-304.137-bionic-18.04.patch
./nvidia-installer
