#!/bin/bash

trap '' INT TSTP

# Verifica se o usuário tem permissão de execução do script: usuário root
if [[ $EUID -ne 0 ]]; then
   clear ; echo " " ; echo "Esse script deve ser executado como usuário root."; echo "Pressione uma tecla para encerrar..." ; echo " " ; read tecla ; clear ; exit ; exit
else
# .: ADICIONAR / REMOVER USUARIO(S) :.
clear
x="menu"
menu ()
{
while true $x != "menu"
do
clear ; echo " " ; echo "ADICIONAR / REMOVER USUARIO(S)" ; echo "------------------------------" ; echo " " ; echo "Usuário(s) ativo(s): " ; grep /home/ /etc/passwd | cut -d: -f1 ; echo " " ; echo -e "1) Criar usuário\t\t2) Remover usuário\t\t3) Encerrar" ; echo " " ; echo -n "Escolha [1-3]: " ; read x
case "$x" in
    1) clear ; echo " " ; echo -n "Digite o nome do novo usuário (apenas letras e números): " ; read nnu ; nnu=`echo $nnu | tr '[:upper:]' '[:lower:]'` ; useradd -m -g users -G autologin,wheel,storage,power -s /bin/bash $nnu ; sleep 1 ; passwd $nnu ; chsh -s /bin/zsh $nnu ;;
    2) clear ; echo " " ; echo -n "Digite o nome do usuário a ser removido: " ; read dun ; userdel -r -f $dun ;;
    3) break ;;
esac
done
}
menu
fi
clear
