#!/bin/bash

# converte iso do arch em iso do artix
# local /usr/local/bin
# chmod +x /usr/local/bin/*

mv /etc/pacman.conf /etc/.pacman.conf ; mv /etc/pacman.d/mirrorlist /etc/pacman.d/.mirrorlist ; cp /root/artix-conf/mirrorlist* /etc/pacman.d/ ; cp /root/artix-conf/pacman.conf /etc/
pacman-key --init ; pacman-key --populate archlinux ; pacman-key --populate artix
pacman -Sy --needed --noconfirm archlinux-keyring artix-keyring ; pacman -Sy --needed --noconfirm artools-base git wget curl
git clone https://github.com/binolinux/artix
clear ; echo ; echo "Copiando arquivos. Aguarde..." ; echo ; cp -a /root/.tmp /mnt/temp ; cp -a /root/artix /mnt/

exit
